apiVersion: apps/v1
kind: Deployment
metadata:
  name: cocktail-manager-cocktail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cocktail-manager-cocktail
  template:
    metadata:
      labels:
        app: cocktail-manager-cocktail
    spec:
      containers:
        - name: cocktail-manager-cocktail
          image: us-central1-docker.pkg.dev/cocktailmanager/cocktail-manager-auth/cocktail-manager-cocktail:latest
          ports:
            - containerPort: {{ .Values.env.port }}
          env:
            - name: PORT
              value: "{{ .Values.env.port }}"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: DATABASE_URL
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: JWT_KEY
            - name: BDD_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: BDD_USER
            - name: BDD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: BDD_PASSWORD
            - name: BDD_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: BDD_NAME
          resources:
            limits:
              memory: '512Mi'
              cpu: '0.5'
            requests:
              memory: '256Mi'
              cpu: '0.1'
