apiVersion: v1
kind: Service
metadata:
  name: cocktail-manager-cocktail-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
  selector:
    app: cocktail-manager-cocktail